rust/src/proofs/api.rs

When using `anyhow` there is a huge difference between the debug output
and the display output. The display output is only the most recent
message text. The debug output contains also all the causes of the error
including a backtrace.

feat: use debug formatting for error messages

---

rust/cbindgen.toml

The `extern "C"` had one curly bracket too much.
Fixes #22.

fix: proper extern C block

---

Makefile
README.md

There is no need to create a `.install-filecoin` file
I'm not sure if I might not miss something and the `.install-filecoin` file is needed somehow.

fix: remove reference to .install-filecoin file

---

proofs.go

Everytime I lint in gfc this gets properly linted (because it is vendors dir as submodule).  I'm fixing it here so I can stop checking out the correct lint stuff.

style: run gofmt -l -s -w

---

.circleci/config.yml
proofs.go
proofs_test.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/lib.rs
rust/src/util/api.rs
rust/src/util/mod.rs
rust/src/util/types.rs

A new FFI call (`util::get_gpu_devices()`) is introduced. It returns
the available GPUs as an array of strings.
I consider it ready for review. The tests will pass once https://github.com/filecoin-project/bellman/pull/31 is merged and released.

feat: get GPU devices via FFI

---

.circleci/config.yml
go.mod
go.sum
proofs.go
proofs_test.go
rust/Cargo.lock
rust/src/proofs/api.rs
rust/src/proofs/helpers.rs
rust/src/proofs/types.rs

Note that this branch is based off of the `feat/drop-custom-types` branch - so that'll need to merge before this merges.
We need to upgrade to the latest and greatest Groth parameters.
This PR upgrades to use the newest (v23) Groth parameters and updates the tests to use the newly-supported 2KiB sector size.

consume new v23 Groth parameters

---

.circleci/config.yml
go.mod
go.sum
proofs.go
proofs_test.go
rust/Cargo.lock
rust/src/proofs/api.rs
rust/src/proofs/helpers.rs
rust/src/proofs/types.rs
types.go

We need to upgrade to the latest and greatest Groth parameters.
This PR upgrades to use the newest (v23) Groth parameters and updates the tests to use the newly-supported 2KiB sector size.

the big cutover to v23 Groth parameters

---

proofs.go

A debug function slipped into the public API (my fault) a week and a half ago. It should be deleted.
We should delete this debug function.

remove debug function which should not have been committed

---

proofs.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/bls/api.rs
rust/src/proofs/api.rs
rust/src/proofs/types.rs

- Pull in bls update https://github.com/filecoin-project/bls-signatures/pull/24
- Add `ClearCache` method
- Pull in changes for piece commitment computation (avoiding tmp dir)

feat: update bls and latest versions of rust-fil-proofs

---

rust/src/proofs/api.rs
rust/src/proofs/helpers.rs

Only 192 of the 1728 seal proof-bytes were making their way to the rust-fil-proofs seal verification function.
This PR fixes a bug in which we dropped all but the first proof partition's worth of seal proof-bytes in the pointer-to-vector conversion function. All the chunking (by partitions) happens in rust-fil-proofs.

bugfix: verification of proofs for 32GiB sectors

---

Makefile
README.md

This reverts commit bbff56c621856352ac9d05540a32c5c48a2861fb.
This is a partial revert. It keeps the simplified instruction in the
README, but still does the Makefile tricks so that it works well with
parallel make. It also adds a comment about it, so that it doesn't
get removed again in the future.

Revert "fix: remove reference to .install-filecoin file (#20)"

---

bls.go
bls_test.go
types.go

See [this thread](https://github.com/filecoin-project/filecoin-ffi/issues/38).
From @frrst:
> Nondeterministic key generation makes testing hard and I am having to hack around it.

add PrivateKeyGenerateWithSeed

---

generated/cgo_helpers.go
generated/generated.go
generated/types.go
rust/src/proofs/api.rs
rust/src/util/api.rs
rust/src/util/types.rs

The file is usually a pipe that was opened by the caller.
This feature was requested by @lanzafame (and earlier explored together with @Kubuxu iirc).
There are no Go binding yet, which I guess can be generated.

feat: make logging to file possible

---

rust/build.rs

`cargo:rerun-if-changed` calls do not recursively check files in directories. Hence
`cargo:rerun-if-changed=src/` would only rebuilds if the directory itself changes,
but won't if the contents changes.
Luckily the `build.rs` is run if any Rust source file changes, hence we don't need
that instruction.
Fixes #28.

fix: rebuild filecoin.h on code changes

---

install-filcrypto

Due to a shellcheck warning, I've put quotes around that instruction,
that broke the actual code.

 fix: make the instruction detection work again 

---

rust/src/util/api.rs

OSX also doesn't support `libc::pipe2`, hence run the test on Linux only.

test: run logging with pipe test on Linux only

---

.circleci/config.yml
generated/cgo_helpers.go
generated/generated.go

The c-for-go binary generates code that, under certain conditions, produces ENOMEM errors. A very helpful user, @dtynn, has patched c-for-go - but [their patch has yet to be merged into upstream](https://github.com/xlab/c-for-go/pull/91).
This PR updates CGO bindings to those generated by dtynn's patch. It also updates CircleCI to generate using that same, forked c-for-go.
With the last lotus network reset, we are no longer able to reproduce this issue. So, we don't know if this patch actually fixes the issues. We're going to merge, deploy, and if it causes problems - we'll revert and pursue some other fix.

use dtynn's forked c-for-go to regenerate CGO bindings

---

.circleci/config.yml
generated/const.go
generated/generated.go
generated/types.go
parameters.json
rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/types.rs

The 26th version of Groth parameters will shortly be ready; the 25th is a thing of the past. Let's get with the times!
This changeset modernizes our stack to the newest, most excellent version of Groth parameters possible.

update to v26 Groth parameters

---

go.mod
go.sum
proofs.go
workflows.go

@whyrusleeping attempted to [bench a 64GiB sector](https://filecoinproject.slack.com/archives/CP50PPW2X/p1589171154210100) and received an error `no mapping to C.FFIRegisteredSealProof value available for: 17`). Turns out that lotus was using specs-actors 0.4.1 and filecoin-ffi was using 0.3.0, which doesn't support 64GiB sectors.
This PR updates specs-actors to 0.4.1 and all corresponding enum-mapping functions.

upgrade to specs-actors 0.4.1 (64GiB sector support)

---

rust/Cargo.lock
rust/src/proofs/api.rs

For more information, see [this Slack thread](https://filecoinproject.slack.com/archives/CEGB67XJ8/p1589207615244400).

don't flatten PoSt proofs - preserve the tuple of version and proof

---

rust/Cargo.lock

The purpose of this commit is to get [this rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs/pull/1101) patch into filecoin-ffi.

fix: use single replica file when using sub-trees

---

proofs.go

The winning PoSt for 64 GiB is missed

add winning PoSt for 64 GiB

---

proofs.go

For more background, see [this thread](https://filecoinproject.slack.com/archives/GTWHXDG0K/p1588866544131500).
Occasionally, operators would report that piece CID generation would produce the following error:
```
0: failed to populate data
1: Bad file descriptor (os error 9)
```
This changeset moves the `runtime.KeepAlive` calls to after the point in which the FFI call returns, which ensures that if we garbage collect in the middle of a CGO call that we don't reap the file descriptor backing the `*os.File`.

don't let Go garbage collect FD until FFI call returns

---

CHANGELOG.md
README.md
mkreleaselog

We need to get in the habit of combining a release with a changelog update so that we can easily communicate the features and bugfixes that go out with each release.
This changeset includes a changelog starting at v0.25.0 to current. It also includes a changelog-generating script which is [based off of the tool which go-ipfs uses](https://github.com/ipfs/go-ipfs/blob/master/bin/mkreleaselog).

add changelog and changelog generator

---

CHANGELOG.md

This PR adds notes (changelog, etc.) for the 0.27.0 release. 
Two things:
1. I will create a PR like this each time I release filecoin-ffi.
1. I will tag @magik6k @anorth @icorderi to review each of these release notes PRs so that they know that we've released software and so that they know what software we released.

add release notes for 0.27.0

---

proofs.go
proofs_test.go

Fixes #94 .
Running `GeneratePieceCommitment` in a loop can occasionally produce (depending on the quantity of iterations) a `too many open files` error.
In Go, the file descriptor associated with an `*os.File` is cleaned up when the file is closed or when the `*os.File` is garbage collected. This changeset adds an explicit `File#Close` call instead of relying on garbage collection to free the file descriptor. When run in a loop, this keeps the file descriptor list at a constant size.

explicitly close os.File to force release of file descriptor

---

CHANGELOG.md

This PR updates our changelog to reflect the latest (and greatest) libfilcrypto release(s).

changelog for 0.28.0, 0.28.1, and 0.29.0

---

CHANGELOG.md

This PR updates our changelog to reflect the latest (and greatest) libfilcrypto release(s).

update changelog for 0.30.0 release

---

.circleci/config.yml
generated/generated.go
rust/Cargo.lock
rust/src/proofs/api.rs
rust/src/util/api.rs

~Note that [this PR](https://github.com/filecoin-project/rust-fil-proofs/pull/1186) needs to be merged and available through rust-filecoin-proofs-api before this PR can be merged.~ done
CircleCI should run the Rust tests in addition to the Go tests.
This PR modifies the CircleCI config to run the Rust tests. It also fixes a bug in the Rust tests which caused a double free-failure.

run the Rust tests before running the Go tests

---

bls.go
bls_test.go

An error from fil_aggregate is encoded as a NUL byte. Unlike other FFI "Response" structs, there is no error code and message. As such, we need to check for the Go nil value before dereferencing the inner signature (which produced a nil-pointer exception today).

handle null pointer returned from fil_aggregate

---

generated/cgo_helpers.go
generated/generated.go
generated/types.go
go.mod
proofs.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/api.rs
rust/src/proofs/types.rs

If Window PoSt fails, return the faulty sectors. They are part of the
error response. The `faulty_sectors_len` is the number of faulty sectors
(0 if there aren't any faulty sectors) and `faulty_sectors_ptr` points
to an array of unsigned 64-bit integers, representing the sector IDs.

feat: return faulty sectors

---

build.sh
distributed.go
generated/cgo_helpers.go
generated/customallocs.go
generated/dummy.go
generated/generated.go
generated/types.go
go.sum
proofs.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/api.rs
rust/src/proofs/types.rs

Relies on https://github.com/filecoin-project/rust-fil-proofs/pull/1283 and https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/41
~~This work does NOT yet include the proofs.go updates required.  I will look at that next unless @magik6k or @Kubuxu can get to it quicker.~~
@dignifiedquire This may have issues, but I fixed the specific nastiness I was fighting earlier.

Add distributed PoSt API

---

.circleci/config.yml
build.sh
filcrypto.yml
generated/cgo_helpers.go
generated/const.go
generated/generated.go
generated/types.go
install-filcrypto
run_tests.sh
rust/Cargo.lock
rust/Cargo.toml

feat: proofs-aip v5.3.0 (new blst backend and optimizations)

---

version.go

To avoid issues similar to the most recent upgrade where,
interface did not change but new proof type got introduced and some
users did not upgrade filecoin-ffi in Lotus.

Add Version const

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/bls/api.rs

feat(rust): integrate new blst based bls-signatures

---

.circleci/config.yml
README.md
install-filcrypto
rust/Cargo.lock
rust/Cargo.toml

This PR adds a blst portable option by adding a build flag `FFI_USE_BLST_PORTABLE=1`.
This PR also uses the portable option when building and publishing the standard blst pre-built binary (for maximum compatibility).
Requires https://github.com/filecoin-project/blstrs/pull/17 and https://github.com/filecoin-project/bls-signatures/pull/34

feat: add blst-portable option for compatibility

---

README.md
build.sh
install-filcrypto
rust/Cargo.lock
rust/Cargo.toml

feat: add support for `gpu` and `gpu2` features
docs: add notes about GPU related features to the readme

feat: update to the latest version of proofs and other deps

---

rust/scripts/package-release.sh

Currently release tarballs contain temporary path in filenames.
It requires extra scripting to extract and use the files (e.g. using `find`).
```
$ tar -tf <(curl -Ls https://github.com/filecoin-project/filecoin-ffi/releases/download/1d9cb3e8ff53f51f/filecoin-ffi-Darwin-standard-pairing.tar.gz)
var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmp.M9Jia6UQ/filcrypto.h
var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmp.M9Jia6UQ/filcrypto.pc
var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmp.M9Jia6UQ/libfilcrypto.a
```
This PR suggests changes that make tarball paths clear and simple like
```
filcrypto/filcrypto.h
filcrypto/filcrypto.pc
filcrypto/libfilcrypto.a
```

Remove tmp prefix from tar path

---

rust/scripts/package-release.sh

Reverts filecoin-project/filecoin-ffi#158 - it breaks the publish CI -> https://app.circleci.com/pipelines/github/filecoin-project/filecoin-ffi/975/workflows/37041e94-3dea-4c02-9878-f2c2369c2531/jobs/5277
```
...
+ trap '{ rm -rf $__tmp_dir; }' EXIT
+ mkdir /tmp/tmp.GpgYd9uoil/filcrypto
+ find -L . -type f -name filcrypto.h -exec cp -- '{}' /tmp/tmp.GpgYd9uoil/filcrypto ';'
+ find -L . -type f -name libfilcrypto.a -exec cp -- '{}' /tmp/tmp.GpgYd9uoil/filcrypto ';'
+ find -L . -type f -name filcrypto.pc -exec cp -- '{}' /tmp/tmp.GpgYd9uoil/filcrypto ';'
+ tar -czf /tmp/filecoin-ffi-Linux-standard-pairing.tar.gz -C /tmp/tmp.GpgYd9uoil 'filcrypto/*'
tar: filcrypto/*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
+ rm -rf /tmp/tmp.GpgYd9uoil …
```

Revert "Remove tmp prefix from tar path"

---

.circleci/config.yml
README.md
build.sh
install-filcrypto
rust/Cargo.lock
rust/Cargo.toml
rust/scripts/build-release.sh
srs-inner-product.json

This PR is based on https://github.com/filecoin-project/filecoin-ffi/pull/192. It adds a custom version of `opencl3` and `cl3` which should fix linker issues on MacOS. The issue there is that it only supports OpenCL 1.2, and by default `opencl3` includes features from newer OpenCL versions. I've also opened an upstream issue: https://github.com/kenba/opencl3/issues/30.

feat: swap pairing for blst (vmx edition)

---

distributed.go
proofs.go
types.go

Merge based on：
https://github.com/filecoin-project/lotus/discussions/6943

* init decoupling-post-worker code

---

parameters.json
rust/Cargo.lock

This PR updates proofs to v11.0.1 and requires the use of production SnapDeal parameters.

feat: update proofs to latest v11.0.1

---

cgo/extern.go
cgo/interface.go
rust/Cargo.lock
rust/src/fvm/cgo.rs
rust/src/fvm/externs.rs

Needs https://github.com/filecoin-project/ref-fvm/pull/330

fvm: return gasused when verifying consensus faults

---

Makefile

Some users may change the default value of [build.target-dir](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir), which will cause this project failed to build.

fix: specify cargo build directory explicitly

---

rust/src/fvm/machine.rs

Can't call `fil_destroy_fvm_machine_flush_response` from C because of type mismatch.  
Removing `const` to fix.
```diff
// generated C header
-const struct fil_FvmMachineFlushResponse *fil_fvm_machine_flush(void *executor);
+struct fil_FvmMachineFlushResponse *fil_fvm_machine_flush(void *executor);
void fil_destroy_fvm_machine_flush_response(struct fil_FvmMachineFlushResponse *ptr);
```

Fix fil_fvm_machine_flush (const)

---

rust/Cargo.lock
rust/Cargo.toml

And switch to rust edition 2021, with the version-2 feature resolver. This fixes the panic in the FVM constructor.
See https://github.com/filecoin-project/filecoin-ffi/pull/251.

fix: completely remove the multihash identity feature

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/machine.rs

This switches to the new bundle method. And makes everything work again.

chore: update fvm & actors

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/blockstore/cgo.rs
rust/src/fvm/blockstore/fake.rs
rust/src/fvm/blockstore/overlay.rs
rust/src/fvm/machine.rs

1. Brings in the shared refactor.
2. Adds nv16 to the network version list.

chore: update fvm

---

cgo/blockstore.go
cgo/errors.go
cgo/extern.go
generated/const.go
generated/generated.go
generated/types.go
rust/src/fvm/cgo/error.rs

Otherwise, we could panic across an FFI boundary, which is undefined behavior.

feat: catch panics in the cgo externs

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/machine.rs
rust/src/fvm/types.rs

- Basic FIP0032 support (nv16+).
- Internal changes.

feat: update FVM to v6.0.0

---

cgo/types.go
rust/Cargo.lock

When the slice pointer is nil, the length is undefined (because the underlying "option" is none). So we return `nil` in this case instead of trying to copy.

fix: copy nil

---

cgo/helpers.go
cgo/helpers_test.go
distributed.go
proofs.go
sector_update.go

They're fine. We can't represent them as null, but rust will internally represent them as 0x1. We could just _assume_ that, but it's safer to call into rust and let it handle this case.
If we don't do this, some of the lotus tests fail.

fix: allow zero-length slice allocs

---

.circleci/config.yml

Waiting for CI can be annoying, hence I thought it makes sense to use large machines where possible. That job is now about a third faster (20 vs 30mins).

chore: CI: use large macOS machine for publishing the FFI

---

rust/Cargo.lock
rust/Cargo.toml

Also upgrades wasmtime to 0.37 (~20% perf improvement in some cases).

chore: upgrade the FVM to 1.0.0-rc2

---

rust/Cargo.lock
rust/Cargo.toml

Otherwise, wasmtime assumes sse4_1 support, and will fail on CPUs that only support SSE2. Unfortunately, I kind of doubt that we'll see a wasmtime release to fix this before we need to ship a release.

fix: backport a fix for SSE feature detection

---

.circleci/config.yml
rust/scripts/build-release.sh
rust/src/lib.rs

This also removes the macos specific and undocumented "build.sh" script.

build: avoid updating the lockfile when building

---

rust/Cargo.lock

This updates the proofs crates to lock the correct dependency versions.

chore: update proofs for v16 release

---

cgo/fvm.go
fvm.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/machine.rs

Companion to https://github.com/filecoin-project/ref-fvm/pull/605

fvm debug execution

---

.circleci/config.yml

- Remove extra build step for build_and_test_linux_cgo_bindings
- Fix build failure in circleci/config.yml to use "go install" to get
paramfetch and install in default GOPATH.
- Add cargo_fetch as requirement to build_and_test_linux_cgo_bindings to
fix intermittent build failure.
- Explicitly install wasm32-unknown-unknown for job build_and_test_linux_cgo_bindings in case that target has not been previously cached by a prior job.

Fix build error and remove extra build step for build_and_test_linux_cgo_bindings

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/machine.rs

This was for testing the upgrade and is no longer necessary or useful. Removing this will shrink the build by a sizable amount.

feat: remove FVM actors-v7 bundle

---

.circleci/config.yml
README.md

Update Xcode docker image for CircleCI and add test badge
- Update to patched CircleCI MacOS Docker image to fix Darwin build
- Add CircleCI status badge and link to project README to link to build and test results

Update CircleCI Xcode image to fix MacOS Darwin Build, and add status badge to readme

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/machine.rs

This is the first step towards getting FFI ready for nv17. The key changes are:
- Integrating the changes to TokenAmount in the FVM (introduced in https://github.com/filecoin-project/ref-fvm/pull/716)
- Integrating the FVM's support for Gas Tracing (introduced in https://github.com/filecoin-project/ref-fvm/pull/709, draft integration into the FFI was [here](https://github.com/filecoin-project/filecoin-ffi/pull/316))
Needs https://github.com/filecoin-project/ref-fvm/pull/861 and (maybe?) an FVM pre-release of v2.

Upgrade to FVM release/v2

---

rust/Cargo.lock
rust/Cargo.toml

This also removes the patch pointing at our fork. We needed that to backport a fix ahead of the M1 release, but it's no longer necessary.

chore: update fvm to 2.0.0

---

rust/Cargo.lock
rust/Cargo.toml

This patches an issue with the `f4-as-account` feature, which temporarily enables embryos to act as senders.

upgrade to fvm@3.0.0-alpha.5 and fvm_shared@3.0.0-alpha.8.

---

cgo/types.go
fvm.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs
rust/src/fvm/machine.rs
rust/src/fvm/types.rs

Part of https://github.com/filecoin-project/ref-fvm/issues/1048.
---
This is the FFI side implementation of https://github.com/filecoin-project/ref-fvm/pull/1049.
FIP at https://github.com/filecoin-project/FIPs/pull/483.
Prior to merging:

propagate actor events and Receipt::events_root.

---

fvm.go

FVM: always create debug FVMs with tracing enabled

---

rust/Cargo.lock
rust/Cargo.toml

Fixes a bug where flushing events would clear the blockstore's write buffer.

chore: update fvm to 3.0.0-alpha.9

---

cgo/blockstore.go
cgo/extern.go

Previously, in cgo, we had to rely on casting pointers to fixed-sized arrays then slicing. But upstream has added an `unsafe.Slice` method, so we can remove this hack.

feat: use the new unsafe.Slice method instead of casting arrays

---

rust/Cargo.lock
rust/Cargo.toml

This will work for mainnet but not for Hyperspace, where the currently-active network version will need to dispatch to fvm v3.0.0-alpha.19, and the following network version will need to dispatch to this.
See https://github.com/filecoin-project/ref-fvm/issues/1627.

upgrade fvm to v3.0.0-alpha.22.

---

Makefile

Go 1.20 changed how `go clean` works
```
$ go clean -cache -testcache .
go: clean -cache cannot be used with package arguments
```

chore: Fix build with Go 1.20

---

rust/src/fvm/engine.rs

We were not setting the chain ID correctly for "v3h1" 😢

fix: set chain id correctly for hyperspace.

---

rust/src/util/types.rs

As the lotus-daemon uses this (a lot), in general you'd like "info" messages from rust - but these are way too noisy in my opinion. 
Dropping them down to debug level.
example from a new block being validated with rust log level on info:
```json
{"level":"info","ts":"2023-02-23T20:58:45.193+0000","logger":"filcrypto::util::types","caller":"src/util/types.rs:200","msg":"fvm_machine_execute_message: end"}
{"level":"info","ts":"2023-02-23T20:58:45.193+0000","logger":"filcrypto::util::types","caller":"src/util/types.rs:198","msg":"fvm_machine_execute_message: start"}
{"level":"info","ts":"2023-02-23T20:58:45.210+0000","logger":"filcrypto::util::types","caller":"src/util/types.rs:200","msg":"fvm_machine_execute_message: end"}
{"level":"info","ts":"2023-02-23T20:58:45.210+0000","logger":"filcryp …
```

Make logs way less noisy

---

rust/src/fvm/machine.rs

This replaces the trace types with FVM specific ones. It:
- Adds codecs to params/return values.
- Removes unset fields like nonce, gas, etc.

feat: plumb codec through lotus trace

---

.circleci/config.yml
rust/scripts/publish-release.sh

This version relies on CircleCI's tag filter to only run the publish jobs on tags. The prior version didn't work because we were only running workflows on commits, not tags.
Everything was working fine for the release branch because the release branch was cut before that change was made.

ci: publish releases on tag (fixed)

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/api.rs

This updates the proofs and the FVM, getting rid of a bunch of deprecated dependencies in the process.

chore: update proofs

---

.circleci/config.yml
README.md
install-filcrypto
rust/Cargo.toml
rust/scripts/build-release.sh

If CUDA is found in the environment, it will be enabled unless `FFI_USE_OPENCL=1` is set.  If CUDA is not found by default or if building on Darwin, OpenCL will be used instead.  If `FFI_NO_GPU=1`, no GPU support will be used.

Enable CUDA as default GPU backend if available

---

rust/src/fvm/engine.rs
rust/src/fvm/machine.rs

Previously, we were limited to 1 message at a time.

feat: make the FVM concurrency configurable and set the default to 4

---

.circleci/config.yml
install-filcrypto

- Rename circleci artifact tarbal names to differentiate x86_64 and aarch64
- Add circleci build, test, and publish for aarch64

Add aarch64 Linux build, test, and publish to CI

---

install-filcrypto

Reading git commit id from environment variable can be useful when building Docker images

chore: attempt to read git commit id from environment variable

---

rust/Cargo.lock
rust/Cargo.toml

This will be needed for users who wish to sync calibnet.

chore: deps: update to FVM 3.3.1 crates

---

.circleci/config.yml
rust/Cargo.lock
rust/scripts/build-release.sh

This change makes CI build things on CUDA (which is the default). It also fixes various other things, like making the `go fmt` job actually work. It also uses smaller instances where it didn't increase the time too much.
---
@magik6k is it a problem to test with the most recent Go 1.18 instead of 1.17.9? I'm asking as this would make the CI significantly simpler as the CircleCI convenience images for Go >= 1.18 already use Ubuntu 22.04, older versions use 20.04.

fix: build for CUDA and other fixes

---

rust/src/fvm/blockstore/cgo.rs

old: 4MiB/1024 blocks.
new: 64MiB/64Ki blocks.
This should work better with network-attached storage. My measurements indicate that we're writing less than 8MiB per epoch and around 4K blocks. Previously, that would have been ~4 writes, now it's always one write and we have room to grow.
fixes https://github.com/filecoin-project/ref-fvm/issues/1786

increase batch-write buffer size

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs
rust/src/fvm/machine.rs

This also unifies both FVM versions on the same ipld encoding crate.
This version also introduces wasm instance "oversubscription" so we can allocate fewer wasm instances (reserve less address space) while specifying a high concurrency factor.

chore: update fvm for wasmtime v10 and cid v0.10

---

cgo/extern.go
cgo/interface.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/cgo/externs.rs
rust/src/fvm/engine.rs
rust/src/fvm/externs.rs

- lands the FVM breaking changes in #348 
- Adds support for nv21

Support nv21

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs

This will allow for Lotus master to run nv21 code behind the feature flag.

feat: nv21: supply nv21-dev flag to FVM3

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs
rust/src/fvm/machine.rs

Related: https://github.com/filecoin-project/ref-fvm/issues/1793 and https://github.com/filecoin-project/fvm-pm/issues/613
Relevant PR in ref-fvm: https://github.com/filecoin-project/ref-fvm/pull/1823
Relevant PR in Lotus: https://github.com/filecoin-project/lotus/pull/11100
This PR updates the rust bindings to include the new fields introduced in https://github.com/filecoin-project/ref-fvm/pull/1823.
Will rebase and update PR once https://github.com/filecoin-project/ref-fvm/pull/1823 lands which should address CI errors.

feat: add new fields to message trace for supporting new trace api

---

cgo/const.go
cgo/proofs.go
go.mod
go.sum
proofs.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/api.rs
rust/src/proofs/types.rs

Bring synth porep changes to master

Synthetic PoRep

---

.circleci/config.yml
install-filcrypto

We always create universal binaries when compiling on x86. This means that the aarch64-apple-darwin also needs to be installed. Install that toolchain automatically if it doesn't exist yet.
This change has also been tested for the case when the toolchain already exists. In that case it just reports:
info: component 'rust-std' for target 'aarch64-apple-darwin' is up to date
Thanks @lanzafame for reporting this issue.

fix: install aarch64-apple-darwin toolchain on x86

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs

Bumps the 1.24.0 release branch to use FVM 4.0.0-alpha.4

chore: backport FVM update

---

.circleci/config.yml
README.md
install-filcrypto
rust/Cargo.lock
rust/Cargo.toml

Make it possible to build the FFI with SupraSeal enabled, which should lead to better performance during C2.
This was accidentally removed from the PR at https://github.com/filecoin-project/filecoin-ffi/pull/418.

feat: add FFI_USE_CUDA_SUPRASEAL env variable

---

.circleci/config.yml
cgo/types.go

As Lotus is now using Go 1.20 [1], also upgrade this CI to use 1.20.
This needs slight reformatting to make go fmt happy.
The CircleCI Ubuntu 22.04 image tagged 2023.07.2 is using Go 1.20.4 [2]. Later versions of that image use Go >= 1.21 [3].
[1]: https://github.com/filecoin-project/lotus/pull/11347
[2]: https://discuss.circleci.com/t/linux-machine-executor-2023-q3-update/48580
[3]: https://discuss.circleci.com/t/linux-machine-executor-2023-q4-update/49457

fix: use Go 1.20 on CircleCI

---

cgo/proofs.go
proofs.go
rust/src/proofs/api.rs

The `ClearLayerData` FFI call was accidentally introduced with the Synthetic PoRep. The call does under the hood exactly what `ClearCache` is doing. It was already removed from Lotus in [PR 11352], so that we can remove it here as well (and as a next steps from the Rust side). This reduces the API surface, which is generally a good idea.
[PR 11352]: https://github.com/filecoin-project/lotus/pull/11352

fix: remove ClearLayerData call

---

install-filcrypto
rust/Cargo.lock
rust/Cargo.toml

The `FFI_USE_FIXED_ROWS_TO_DISCARD` variable will make the proofs ignore the `FIL_PROOFS_ROWS_TO_DISCARD` setting, hence not relying on a `t_aux` file to be present. If enabled, then no `t_aux` file will be written by the proofs and a hard-coded value for `FIL_PROOFS_ROWS_TO_DISCARD` will be used.
---
I make this into draft mode as CI currently isn't passing due to https://github.com/filecoin-project/filecoin-ffi/issues/431.

feat: add option to not require a t_aux file to be present

---

rust/src/util/api.rs

SupraSeal has it's own GPU device management. The rest of the system does *not* know, which GPUs will be used/are available. Though some code paths still use the usual Rust based code. Instead of returning no devices, the call to `get_gpu_devices` now returns all devices the Rust based system will use. It's not necessarily the same as SupraSeal will use.

fix: list GPU devices also with SupraSeal

---

install-filcrypto

@rvagg noticed this call getting rate limited:
```
++ curl --retry 3 --location https://api.github.com/repos/filecoin-project/filecoin-ffi/releases/tags/5d00bb4365a97890
++ echo '{"message":"API rate limit exceeded for 208.83.5.75. (But here'\''s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}'
```
The error message suggests using an authenticated call might help with this.

chore: use auth_header when trying to download release tarball

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs
rust/src/fvm/machine.rs

- Supports nv22.
- Cleanups & refactors.
- Changes the trace format a little to include the state-root of every actor when invoked.

Update the FVM to v4.1

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs

Prepering a PR updating FVM to the new FVM-release (v4.1.2) that is coming, due to https://github.com/filecoin-project/ref-fvm/pull/1978

chore: update FVM to v4.1.2 and v3.9.0

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs
rust/src/fvm/machine.rs

We previously used the FVM's `ThreadedExecutor` to execute messages on separate threads because the FVM requires 64MiB of stack space.
1. The FVM v3 supported for 8 concurrent threads.
2. The FVM v4 supports up to the number of CPU threads available.
Unfortunately, neither version was influenced by the `LOTUS_FVM_CONCURRENCY` environment variable.
This patch fixes this by:
1. Moving the thread-pool to the FFI itself (sharing it between FVM versions).
2. Setting the thread-pool size equal to `LOTUS_FVM_CONCURRENCY`.
It also defaults `LOTUS_FVM_CONCURRENCY` to the number of available CPU threads instead of the previous 4.
NOTE: I've also tried increasing the stack size instead of using threads, but Go _does not_ like it when other foreign mess with the stack size of _its_ threads (but it …

Make sure we can reach the user's requested FVM concurrency

---

install-filcrypto
rust/Cargo.lock
rust/Cargo.toml
rust/rust-toolchain.toml
rust/src/bls/api.rs
rust/src/fvm/engine.rs
rust/src/fvm/mod.rs
rust/src/proofs/api.rs

feat: some shell logic re-factoring

feat: update to the improved error handling in proofs

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs

Adds the nv23 skeleton to Filecoin-FFI:
- Update to fvm version 4.2.0
- Add support for nv23
- Updating the cargo.lock file with: `cargo update -p "filecoin-proofs-api@17.0.0"`

feat: Add skeleton for nv23

---

.circleci/config.yml

Use the same rust version on CI as in the rust-toolchain.toml file.

chore: update Rust version on CI to 1.73

---

.circleci/config.yml
install-filcrypto
rust/scripts/build-release.sh

This PR migrated the macos builds in the repo to Apple Silicon executors since the Apple Intel ones are getting deprecated by January 2024. See https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718.
FYI, the builds currently fail with:
```
ld: warning: directory not found for option '-L/usr/lib/aarch64-linux-gnu/stubs'
ld: warning: directory not found for option '-L/usr/lib/aarch64-linux-gnu/stubs'
ld: warning: directory not found for option '-L/usr/lib/aarch64-linux-gnu/stubs'
ld: library not found for -lhwloc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL    github.com/filecoin-project/filecoin-ffi [build failed]
```
I assume it's going to be easier to figure out for maintainers.

ci: switch macos builds to apple silicon and upgrade xcode

---

rust/Cargo.toml

The diff is bigger than necessary because I ran a fmt on the file, but IMO the outcome is a bonus so I'm leaving it. The only real change here is adding `"verify-signature"` to `fvm4`

fix: enable verify-signature on fvm4

---

.circleci/config.yml
cgo/const.go
cgo/proofs.go
go.mod
go.sum
proofs.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/api.rs
rust/src/proofs/types.rs

This commit adds support for ni-porep.
It's a combination of the indivdual PRs #453, #456 and #458. Thanks everyone involved working on those.
The changes are for the Go side (actors and FVM) as well as the Rust side (proofs API).
Changes on the CI are:
- Makes it match the Rust version in the rust-toolchain.toml
- Newer Go version (1.21) on all platforms
- Larger instance for the testsas the Ni-PoRep synthesis phase takes more resources.
Closes #453, #456, #458.
---
I made a new PR containing all changes to make things easier to follow and review.
What is still missing is a new `rust-fil-proofs` release containing https://github.com/filecoin-project/rust-fil-proofs/pull/1758. To keep things simple, it'll probably be a patch release, so the only thing that we'll need will be updating the …

feat: add support for Non-interactive PoRep

---

rust/Cargo.lock
rust/Cargo.toml

Removes the nv23-dev feature, enabling support by default.

chore: update fvm to 4.3.1

---

.github/actions/configure-environment/action.yml
.github/workflows/ci.yml
bls_test.go

In this PR, we migrate the CI from CircleCI to GitHub Actions.
The important difference in the GitHub Actions setup is that we're running the Linux ARM64 builds on self-hosted GitHub Actions runners.
Code style checks, builds, and tests have been tested in CI - see https://github.com/filecoin-project/filecoin-ffi/actions/runs/9857064865
Publishing will only be verified after the merge. 
Before the merge, we have to stop building in CircleCI and change the Required workflows setting.
Once we verify the new workflow works as expected, we're going to remove the CircleCI configuration altogether.
As requested, the GitHub Actions release workflow supports releasing from an arbitrary historical refs using the workflow dispatch trigger with ref input.

ci: migrate ci setup from circle ci to github actions

---

README.md
install-filcrypto

Ref: https://github.com/filecoin-project/lotus/pull/12423
Background: we're having trouble building from source in Lotus CI because we run tests two different machine types and only build FFI on one, caching the output and deploying it on the other machines. We have our own custom runners in AWS and also lean heavily on the default GHA runners which are in Azure and they obviously have different CPU types.
This change introduces `FFI_PORTABLE=1` which builds using the same flags as rust/scripts/build-release.sh does when called from CI to build the release bundle.
Comparison of some builds:
When run from CI, we get:
```
+ RUSTFLAGS='--print native-static-libs '
+ cargo build --release --locked --verbose --no-default-features --features multicore-sdr,opencl,blst-portable
```
When run from …

feat: FFI_PORTABLE to build a maximally portable binary

---

version.json

Cut a v1.30.0-dev release so that we can test out https://github.com/filecoin-project/filecoin-ffi/pull/480 and the nv24-skeleton

chore: 1.30.0-dev release

---

.github/workflows/release-check.yml

Before this, we were trying to `cd rust` twice so the second `cd` was failing.

ci: fix asset publishing in release check workflow

---

install-filcrypto

Avoid the need for using the commit hash to find the release.
Fixes: https://github.com/filecoin-project/filecoin-ffi/issues/491
See #491 for the question of whether we want to lock this behaviour in - release assets are only available for tags, not every commit on master as they used to be with CircleCI.

feat: download release tarball from named release

---

version.json

build: update version to v1.31.0-rc1

build: update version to v1.31.0-rc1

---

version.json

Closes: https://github.com/filecoin-project/filecoin-ffi/issues/490 and https://github.com/filecoin-project/filecoin-ffi/issues/502

chore: create v1.31.0 release

---

.github/workflows/ci.yml

parallel tests and faster runners

---

.github/actions/configure-environment/action.yml

This (pkg-config, specifically) was causing an error in CI due to a conflicting version already being available. It also turns out that `jq` is installed by default in this image as well.

ci: remove unecessary dependencies from macos

---

.github/actions/configure-environment/action.yml
.github/workflows/ci.yml

This fixes the environment configuration on Ubuntu 24.04 arm64 machines.
The context for the fix is that Ubuntu 24.04 comes with glibc 2.39 installed. Using older versions of nvcc with that glibc version results in the following errors - https://bugs.launchpad.net/ubuntu/+source/mumax3/+bug/2032624. This is specific to arm64 builds only.
On the plus side, we no longer have to downgrade gcc.
As a follow-up piece of work, we should consider installing the latest version of CUDA toolkit in the AMIs.
TODO (@galargh):

ci: fix environment configuration on Ubuntu 24.04 arm64

---

cgo/bls.go
cgo/fvm.go
cgo/helpers.go
cgo/proofs.go
cgo/types.go
cgo/util.go

Alternative to #517 that uses newtypes. IMO, this is a bit less risky as we're not introducing any new pointers, wrappers, etc.

refactor: support go 1.24 with newtypes

---

version.json

release v1.32.0-rc2

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs

- Update to ref-fvm v4.6.0
- Add nv26-support
- update cargo.lock

chore: release v1.32.0-rc3

---

version.json

I merged #520 before I noticed that it didn't actually bump the version number (probably wasn't ready yet, oops).

chore: actually release v1.32.0-rc3

---

version.json

chore: bump version to v1.32.0

---

rust/rust-toolchain.toml
rust/src/proofs/api.rs

This is the latest upstream rust version. The assumption is that this version of the FFI _won't_ land in the current stable release of Lotus.

chore: update rust to 1.86.0

---

cgo/fvm.go
fvm.go
rust/src/fvm/engine.rs
rust/src/fvm/machine.rs

Ref: https://github.com/filecoin-project/ref-fvm/pull/2101
This is a draft, but the `ExecutionEvent::Log` could probably be done separately since that's much more likely to actually make it in. I'll do that if I end up bailing on this.

feat: support flush_all_blocks, handle new ipld operations in traces

---

install-filcrypto

This is a follow-up to https://github.com/filecoin-project/lotus/pull/13223
It passes `Accept:application/octet-stream` header in a request which downloads the release assets. This will ensure we can actually download the assets instead of having to build them from source every time.

chore: pass accept header to asset download request

---

cgo/proofs.go
proofs.go
rust/Cargo.lock
rust/Cargo.toml
rust/src/proofs/api.rs

chore: bump filecoin-proofs-api to v19.0
Users will need to update their calls from:
```
// Before
ClearCache(sectorSize, cacheDirPath)
ClearSyntheticProofs(sectorSize, cacheDirPath)
// After  
ClearCache(cacheDirPath)
ClearSyntheticProofs(cacheDirPath)
```
The changes are consistent across all layers and properly remove the unused sector_size parameter completely from the API.

chore: bump filecoin-proofs-api to v19.0

---

.github/actions/upload-release-assets/action.yml
.github/workflows/upload-release-assets.yml
RELEASE.md

This will create a new workflow `Upload Release Assets` which can be used to do emergency release assets uploads when something goes wrong.
I tested it by triggering https://github.com/filecoin-project/filecoin-ffi/actions/runs/17773290672 on push. It is failing because the action I'm adding here is not available in the tag of the release that we were uploading assets to. It's just a false negative.

ci: create release uploader workflow

---

.github/actions/configure-environment/action.yml
.github/workflows/ci.yml
go.mod

This PR updates Go version used in this repo to 1.24.7.
golangci-lint v1.64 is the last version in the v1 lineage. It has moved on to v2 now. v1.64 does not support Go 1.25 so we'll have to upgrade to v2 before we move on to Go 1.25 ourselves.

chore!: upgrade to Go 1.24

---

rust/Cargo.lock
rust/Cargo.toml
rust/src/fvm/engine.rs

Depends on: https://github.com/filecoin-project/ref-fvm/pull/2220 and a new ref-fvm release. Once that is out, will update the lock file.
Closes: #547

chore: add nv28 skeleton
