proofs.go, proofs_test.go, rust/Cargo.lock, rust/Cargo.toml, rust/src/proofs/api.rs, rust/src/proofs/types.rs
=> feat(proofs): add unseal_range

rust/Cargo.lock
@DrPeterVanNostrand wrote some software which speeds stuff up. We want speedier stuff.
=> feat(upstream): upgrade sapling crypto to 0.2.2 for perf

rust/Cargo.lock
pulls in https://github.com/filecoin-project/rust-fil-proofs/pull/976
=> fix(rust): pull in fix for label store sizes

rust/Cargo.lock
and some other improved error handling
=> fix: cache path handling

rust/Cargo.lock
ref https://github.com/filecoin-project/rust-fil-proofs/pull/985/
=> feat(rust):  params v20-1

.circleci/config.yml
Fixes #23.
Please note that I don't have a clue about CircleCI. I was just trial and erroring it. So this should be reviewed by someone knowing CircleCI.
=> fix: do releases only when building the master branch

.circleci/config.yml, rust/Cargo.lock, rust/Cargo.toml, rust/src/bls/api.rs
This is meant for testing in order to be able to deterministically generate keys.
Please merge this with "rebase & merge" as the second commit is unrelated to the work and just a fix to get CI green.
=> feat: allow private key generation with a seed 

.circleci/config.yml, rust/src/bls/api.rs, rust/src/proofs/api.rs, rust/src/proofs/helpers.rs, rust/src/proofs/types.rs, rust/src/util/api.rs
=> Run clippy and rustfmt on CI

.circleci/config.yml, Makefile
We gotta lint our codes, right? And we want to make sure our stuff is `gofmt`'ed.
=> rework CircleCI config + add linting and gofmt jobs

.circleci/config.yml, Makefile, install-filecoin
Some fixes, mostly based on a shellcheck run.
=> Improving the bash script quality

rust/src/bls/api.rs, rust/src/lib.rs, rust/src/proofs/api.rs, rust/src/proofs/helpers.rs, rust/src/proofs/types.rs, rust/src/util/api.rs
I thought now is a good time to beautify the code base a bit. It's a pure refactor without any functiona changed.
=> Cosmetic changes

README.md
=> docs: add instructions for `go get`

rust/src/util/api.rs
The file logger needs to be initialized as the first action when calling the
FFI. If there was already any logger initialized, return an error when trying
to initialize the file logger.
=> fix: error if there is already a logger

CHANGELOG.md
Adds release notes for 0.30.1.
=> 0.30.1 changelog

CHANGELOG.md
This PR updates the changelog for 0.30.2 and 0.30.3.
=> add changelog entries for 0.30.2 and 0.30.3

bls_test.go
=> aggregateSign test

.circleci/config.yml, build.sh, generated/const.go, generated/generated.go, generated/types.go, go.mod, go.sum, proofs.go, rust/Cargo.lock, rust/Cargo.toml, rust/src/proofs/api.rs, rust/src/proofs/types.rs, rust/src/util/api.rs, workflows.go
feat: test legacy and non-legacy registered seal proof types
=> feat: proofs upgrade for sdr expander truncation

.circleci/config.yml, bls.go, cgo/blockstore.go, cgo/extern.go, cgo/registry.go, filcrypto.yml, fvm.go, generated/cgo_helpers.go, generated/const.go, generated/generated.go, generated/types.go, proofs.go, rust/Cargo.toml, rust/scripts/build-release.sh, rust/src/fvm/blockstore.rs, rust/src/fvm/machine.rs
- Register a contexts along with Externs.
- Address misc TODOs & FIXMEs.
=> fvm: pass contexts and address TODOs

rust/src/fvm/machine.rs
Rust uses 0x1, not 0x0, for "empty" types/slices/etc. Go panics when it encounters a pointer to 0x1 (really, anything that's not zero and that's less than some cutoff).
This fix just laves the return pointer as null unless it's non-empty.
=> fvm: fix invalid return bytes pointer

fvm.go, generated/generated.go, rust/src/fvm/machine.rs
Required for https://github.com/filecoin-project/lotus/pull/8429
Blocked on https://github.com/filecoin-project/ref-fvm/pull/448 and crate release
Note: Cargo points to my local dev env, which will make CI very angry. I will update once https://github.com/filecoin-project/ref-fvm/pull/448 merges and the crate is released.
=> Update fvm integration for FIP0031

rust/Cargo.lock, rust/Cargo.toml
This version builds on aarch64.
=> chore: upgrade fvm

rust/Cargo.lock, rust/Cargo.toml
No integration work needed on this end of things.
=> Update FVM to 0.7.0

fvm.go, generated/cgo_helpers.go, generated/generated.go, generated/types.go, rust/src/fvm/machine.rs, rust/src/fvm/types.rs
This PR sets the ActorError to propagate backtrace information.
=> feat: propagate backtraces as errors

rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/machine.rs
Depends on https://github.com/filecoin-project/ref-fvm/pull/494
=> fvm: Engine per network

rust/Cargo.lock, rust/Cargo.toml
And also upgrade other deps in Cargo.lock.
=> integrate fvm v1.0.0-rc.1 and builtin-actors v7.5.0.

rust/src/fvm/blockstore/cgo.rs
Suggested by @wadeAlexC, thanks!
=> chore: use fvm::MAX_CID_LEN

cgo/fvm.go, fvm.go, rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/machine.rs
Oops, forgot to undo the branch patching -- that needs a release of the FVM.
=> Revert #288

rust/Cargo.lock, rust/Cargo.toml
=> Update FVM to 1.0.0

cgo/types.go, proofs.go
=> backport: fix #307 (#308)

rust/src/fvm/machine.rs
=> fix: LotusTrace: don't add new events_root field to Receipt

cgo/fvm.go, fvm.go, rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/engine.rs, rust/src/fvm/machine.rs
Also integrates recent changes to the Engine, but doesn't configure them.
=> FVM: Set chain ID when creating machine

rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/engine.rs, rust/src/fvm/machine.rs
=> Update to FVM 3.0.0-alpha.17

rust/src/fvm/externs.rs
Thou shalt not copy paste code.
=> externs: get_tipset_cid: fix error message

rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/engine.rs, rust/src/fvm/machine.rs
1. Updates to the latest gas fees.
2. Adapts to the changes in gas tracing (half way). We still need to propagate this information to lotus, but that's a future patch.
=> chore: update FVM

rust/src/fvm/engine.rs
=> fix: correctly convert v2 RawBytes in traces into an Option<IpldBlock>

rust/src/fvm/machine.rs
So that we get _all_ the charges in Lotus, including things like `OnChainMessage`.
Draft until fully integrated into Lotus.
=> feat: fvm: pass all GasCharges to the client

rust/src/fvm/engine.rs, rust/src/fvm/machine.rs
We were catching panics here, but the unwraps ended up hiding the actual error message because rust backtraces are disabled by default.
=> fix: fvm: remove all unwraps

rust/src/fvm/engine.rs
=> FVM3: Support nv19 and 20

rust/Cargo.lock, rust/Cargo.toml, rust/src/proofs/api.rs, rust/src/proofs/types.rs
~~Ready to go for review/testing, but does require proofs releases to be referenced, rather than git `master` branches.~~
Good to go! :rocket:
=> feat: implement FIP-0061

rust/src/fvm/machine.rs
This reverts commit b17eb3b93be475d74775ee1f8ee3ed7560fa0910 on the lotus/release-1.22.0 branch only.
=> Revert "feat: plumb codec through lotus trace (#379)"

build.sh, cgo/proofs.go, proofs.go, rust/Cargo.lock, rust/Cargo.toml, rust/src/proofs/api.rs, rust/src/proofs/types.rs
Those new APIs are about:
- decoding a range of an updated empty sector
- generating TreeRLast
- generating TreeC
- running SDR
=> feat: add various new APIs for Lotus

README.md
chore: Updates and fixes in README.md, including the current versioning scheme for Filecoin-FFI and how to cut a release.
=> chore: Updates and fixes in README.md

rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/engine.rs
=> chore: add nv-24 skeleton

version.json
Testing release process after fixes to the underlying workflows.
=> chore: release v1.30.0-dev2

version.json
=> chore: release v1.30.0-rc1

rust/Cargo.lock, rust/Cargo.toml
=> chore: update FVM to v4.3.3

version.json
=> chore: release v1.30.0-rc2

rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/engine.rs
Ref: https://github.com/filecoin-project/filecoin-ffi/issues/502
Add nv25 skeleton.
=> chore: add nv25 skeleton

rust/Cargo.lock, rust/Cargo.toml, rust/src/fvm/machine.rs
And update the rest of the dependencies.
=> chore: update ref-fvm to v4.7, v3.13, and v2.11

version.json
Publishes a release that has https://github.com/filecoin-project/filecoin-ffi/pull/534 included, so that we can get build tests passing in: https://github.com/filecoin-project/lotus/pull/13220
=> chore: 1.33.1-dev2 release

version.json
chore: bump version to v1.34.0-dev
=> chore: bump version to v1.34.0-dev
